apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-podinfo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://stefanprodan.github.io/podinfo
    chart: podinfo
    targetRevision: 6.7.1
    helm:
      releaseName: demo-podinfo
      values: |
        replicaCount: 1
        ingress:
          enabled: false
        serviceMonitor:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
