#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

: "${GITHUB_TOKEN:?GITHUB_TOKEN must be set so ArgoCD can read this repo (Phase 4+ uses it)}"

HUB_CTX="kind-hub"
ARGOCD_NS="argocd"
ARGOCD_VERSION="${ARGOCD_VERSION:-7.6.12}"   # Helm chart version that ships ArgoCD 2.12.x

kctl() { kubectl --context "$HUB_CTX" "$@"; }

# 1. Install ArgoCD via Helm. Idempotent.
helm repo add argo https://argoproj.github.io/argo-helm >/dev/null 2>&1 || true
helm repo update argo >/dev/null

helm upgrade --install argocd argo/argo-cd \
  --kube-context "$HUB_CTX" \
  --namespace "$ARGOCD_NS" \
  --create-namespace \
  --version "$ARGOCD_VERSION" \
  --set configs.params."server\.insecure"=true \
  --set applicationSet.enabled=true \
  --wait --timeout 5m

# 2. Patch the ApplicationSet ClusterRole and the cmd-params ConfigMap.
kctl apply -f manifests/applicationset-clusterrole-patch.yaml
kctl apply -f manifests/argocd-cmd-params-cm.yaml

kctl -n "$ARGOCD_NS" rollout restart \
  statefulset/argocd-application-controller \
  deployment/argocd-applicationset-controller
kctl -n "$ARGOCD_NS" rollout status statefulset/argocd-application-controller --timeout 3m
kctl -n "$ARGOCD_NS" rollout status deployment/argocd-applicationset-controller --timeout 3m

# 3. Register the spokes as ArgoCD cluster Secrets.
#
# Direct kubectl is intentional. The argocd CLI's cluster add path goes
# through the gRPC API and is unreliable on macOS + kind. Writing the
# Secret directly removes that hop.
#
# kind get kubeconfig --internal returns the API server address as the
# kind container hostname rather than 127.0.0.1, so the hub container can
# reach the spoke container over Docker's user-defined network.
register_spoke() {
  local name="$1"
  local tmp; tmp=$(mktemp)
  kind get kubeconfig --name "$name" --internal > "$tmp"

  local kc_json server ca_data cert_data key_data
  kc_json=$(KUBECONFIG="$tmp" kubectl config view --raw --minify -o json)
  rm -f "$tmp"

  server=$(echo "$kc_json"   | jq -r '.clusters[0].cluster.server')
  ca_data=$(echo "$kc_json"  | jq -r '.clusters[0].cluster["certificate-authority-data"]')
  cert_data=$(echo "$kc_json" | jq -r '.users[0].user["client-certificate-data"]')
  key_data=$(echo "$kc_json"  | jq -r '.users[0].user["client-key-data"]')

  kctl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: cluster-${name}
  namespace: ${ARGOCD_NS}
  labels:
    argocd.argoproj.io/secret-type: cluster
    cluster.platform/env: ${name}
type: Opaque
stringData:
  name: ${name}
  server: ${server}
  config: |
    {
      "tlsClientConfig": {
        "caData": "${ca_data}",
        "certData": "${cert_data}",
        "keyData": "${key_data}"
      }
    }
EOF
  echo "[bootstrap] registered spoke: ${name} (${server})"
}

register_spoke dev
register_spoke prod

# 4. Apply the platform manifests generated by KCL (AppProjects + the
#    simpleOnboarding ApplicationSet for every project in ManagedProjects).
kctl apply -f ../manifests/main.yaml

# 5. kube-prometheus-stack on the hub. Platform infra, hand-written
#    Application rather than ApplicationSet output. Per-team rules and
#    dashboards arrive via the monitoring-onboarding ApplicationSet above.
kctl apply -f manifests/kube-prometheus-stack-app.yaml
kctl -n "$ARGOCD_NS" wait --for=condition=Available=true \
  --timeout=10m application/kube-prometheus-stack || true
kctl -n monitoring rollout status statefulset/prometheus-kube-prometheus-stack-prometheus --timeout 5m || true
kctl -n monitoring rollout status statefulset/alertmanager-kube-prometheus-stack-alertmanager --timeout 5m || true
kctl -n monitoring rollout status deployment/kube-prometheus-stack-grafana --timeout 5m || true

# 6. Vault server in dev mode + vault-secrets-operator. Hub-only.
kctl apply -f manifests/vault-app.yaml
kctl apply -f manifests/vault-secrets-operator-app.yaml

kctl wait --for=condition=Available --timeout=5m \
  -n "$ARGOCD_NS" application/vault || true
kctl -n vault rollout status statefulset/vault --timeout 5m
kctl -n vault wait --for=condition=Ready pod/vault-0 --timeout 3m

kctl wait --for=condition=Available --timeout=5m \
  -n "$ARGOCD_NS" application/vault-secrets-operator || true
kctl -n vault-secrets-operator-system rollout status \
  deployment/vault-secrets-operator-controller-manager --timeout 5m

# 7. Imperative Vault seed: per-team policies, k8s auth roles, KV secrets.
HUB_CTX="$HUB_CTX" source manifests/vault-bootstrap.sh

echo "[bootstrap] hub + spokes + monitoring + vault ready. Initial ArgoCD admin password:"
kctl -n "$ARGOCD_NS" get secret argocd-initial-admin-secret \
  -o jsonpath='{.data.password}' | base64 -d
echo
echo "[bootstrap] port-forward to view UI:"
echo "  kubectl --context $HUB_CTX port-forward -n $ARGOCD_NS svc/argocd-server 8080:443"
