#!/usr/bin/env bash
set -euo pipefail

HUB_CTX="kind-hub"
kctl() { kubectl --context "$HUB_CTX" "$@"; }

# Wait for every Application generated by the demo ApplicationSet to converge.
deadline=$((SECONDS + 600))
while (( SECONDS < deadline )); do
  pending=0
  while read -r app sync health; do
    [[ -z "$app" ]] && continue
    echo "[verify] $app sync=$sync health=$health"
    if [[ "$sync" != "Synced" || "$health" != "Healthy" ]]; then
      pending=$((pending+1))
    fi
  done < <(kctl -n argocd get applications -o jsonpath='{range .items[?(@.metadata.ownerReferences[0].kind=="ApplicationSet")]}{.metadata.name}{" "}{.status.sync.status}{" "}{.status.health.status}{"\n"}{end}')

  if (( pending == 0 )); then
    echo "[verify] all generated applications converged"
    for ctx in kind-hub kind-dev kind-prod; do
      echo "--- $ctx demo namespace ---"
      kubectl --context "$ctx" -n demo get pods 2>/dev/null | tail -n +1
    done
    exit 0
  fi
  echo "[verify] $pending application(s) still converging"
  sleep 10
done

echo "[verify] not all applications converged within 10m" >&2
kctl -n argocd get applications >&2
exit 1
